/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SettingService } from "../setting.service";
import { SettingCreateInput } from "./SettingCreateInput";
import { Setting } from "./Setting";
import { SettingFindManyArgs } from "./SettingFindManyArgs";
import { SettingWhereUniqueInput } from "./SettingWhereUniqueInput";
import { SettingUpdateInput } from "./SettingUpdateInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

export class SettingControllerBase {
  constructor(protected readonly service: SettingService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Setting })
  async createSetting(
    @common.Body() data: SettingCreateInput
  ): Promise<Setting> {
    return await this.service.createSetting({
      data: data,
      select: {
        createdAt: true,
        id: true,
        notificationPreferences: true,
        privacySettings: true,
        updatedAt: true,
        userId: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Setting] })
  @ApiNestedQuery(SettingFindManyArgs)
  async settings(@common.Req() request: Request): Promise<Setting[]> {
    const args = plainToClass(SettingFindManyArgs, request.query);
    return this.service.settings({
      ...args,
      select: {
        createdAt: true,
        id: true,
        notificationPreferences: true,
        privacySettings: true,
        updatedAt: true,
        userId: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Setting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async setting(
    @common.Param() params: SettingWhereUniqueInput
  ): Promise<Setting | null> {
    const result = await this.service.setting({
      where: params,
      select: {
        createdAt: true,
        id: true,
        notificationPreferences: true,
        privacySettings: true,
        updatedAt: true,
        userId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Setting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSetting(
    @common.Param() params: SettingWhereUniqueInput,
    @common.Body() data: SettingUpdateInput
  ): Promise<Setting | null> {
    try {
      return await this.service.updateSetting({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          notificationPreferences: true,
          privacySettings: true,
          updatedAt: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Setting })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSetting(
    @common.Param() params: SettingWhereUniqueInput
  ): Promise<Setting | null> {
    try {
      return await this.service.deleteSetting({
        where: params,
        select: {
          createdAt: true,
          id: true,
          notificationPreferences: true,
          privacySettings: true,
          updatedAt: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/users")
  @ApiNestedQuery(UserFindManyArgs)
  async findUsers(
    @common.Req() request: Request,
    @common.Param() params: SettingWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findUsers(params.id, {
      ...query,
      select: {
        accessToken: true,
        createdAt: true,
        email: true,
        firstName: true,

        friendship: {
          select: {
            id: true,
          },
        },

        fullName: true,
        id: true,
        instagramId: true,
        lastName: true,
        profilePictureUrl: true,
        refreshToken: true,
        roles: true,

        search: {
          select: {
            id: true,
          },
        },

        setting: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/users")
  async connectUsers(
    @common.Param() params: SettingWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        connect: body,
      },
    };
    await this.service.updateSetting({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/users")
  async updateUsers(
    @common.Param() params: SettingWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        set: body,
      },
    };
    await this.service.updateSetting({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/users")
  async disconnectUsers(
    @common.Param() params: SettingWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        disconnect: body,
      },
    };
    await this.service.updateSetting({
      where: params,
      data,
      select: { id: true },
    });
  }
}
