/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { SearchFindManyArgs } from "../../search/base/SearchFindManyArgs";
import { Search } from "../../search/base/Search";
import { SearchWhereUniqueInput } from "../../search/base/SearchWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: {
        ...data,

        friendship: data.friendship
          ? {
              connect: data.friendship,
            }
          : undefined,

        search: data.search
          ? {
              connect: data.search,
            }
          : undefined,

        setting: data.setting
          ? {
              connect: data.setting,
            }
          : undefined,
      },
      select: {
        accessToken: true,
        createdAt: true,
        email: true,
        firstName: true,

        friendship: {
          select: {
            id: true,
          },
        },

        fullName: true,
        id: true,
        instagramId: true,
        lastName: true,
        profilePictureUrl: true,
        refreshToken: true,
        roles: true,

        search: {
          select: {
            id: true,
          },
        },

        setting: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        accessToken: true,
        createdAt: true,
        email: true,
        firstName: true,

        friendship: {
          select: {
            id: true,
          },
        },

        fullName: true,
        id: true,
        instagramId: true,
        lastName: true,
        profilePictureUrl: true,
        refreshToken: true,
        roles: true,

        search: {
          select: {
            id: true,
          },
        },

        setting: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        accessToken: true,
        createdAt: true,
        email: true,
        firstName: true,

        friendship: {
          select: {
            id: true,
          },
        },

        fullName: true,
        id: true,
        instagramId: true,
        lastName: true,
        profilePictureUrl: true,
        refreshToken: true,
        roles: true,

        search: {
          select: {
            id: true,
          },
        },

        setting: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: {
          ...data,

          friendship: data.friendship
            ? {
                connect: data.friendship,
              }
            : undefined,

          search: data.search
            ? {
                connect: data.search,
              }
            : undefined,

          setting: data.setting
            ? {
                connect: data.setting,
              }
            : undefined,
        },
        select: {
          accessToken: true,
          createdAt: true,
          email: true,
          firstName: true,

          friendship: {
            select: {
              id: true,
            },
          },

          fullName: true,
          id: true,
          instagramId: true,
          lastName: true,
          profilePictureUrl: true,
          refreshToken: true,
          roles: true,

          search: {
            select: {
              id: true,
            },
          },

          setting: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          accessToken: true,
          createdAt: true,
          email: true,
          firstName: true,

          friendship: {
            select: {
              id: true,
            },
          },

          fullName: true,
          id: true,
          instagramId: true,
          lastName: true,
          profilePictureUrl: true,
          refreshToken: true,
          roles: true,

          search: {
            select: {
              id: true,
            },
          },

          setting: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/searches")
  @ApiNestedQuery(SearchFindManyArgs)
  async findSearches(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Search[]> {
    const query = plainToClass(SearchFindManyArgs, request.query);
    const results = await this.service.findSearches(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        imageUrl: true,
        isPrivate: true,
        response: true,
        searchParameters: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        userId: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/searches")
  async connectSearches(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: SearchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      searches: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/searches")
  async updateSearches(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: SearchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      searches: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/searches")
  async disconnectSearches(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: SearchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      searches: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
