/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FeedUpdateManyWithoutSearchesInput } from "./FeedUpdateManyWithoutSearchesInput";

import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsBoolean,
  IsInt,
  Min,
  Max,
} from "class-validator";

import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { UserUpdateManyWithoutSearchesInput } from "./UserUpdateManyWithoutSearchesInput";

@InputType()
class SearchUpdateInput {
  @ApiProperty({
    required: false,
    type: () => FeedUpdateManyWithoutSearchesInput,
  })
  @ValidateNested()
  @Type(() => FeedUpdateManyWithoutSearchesInput)
  @IsOptional()
  @Field(() => FeedUpdateManyWithoutSearchesInput, {
    nullable: true,
  })
  feeds?: FeedUpdateManyWithoutSearchesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  imageUrl?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isPrivate?: boolean | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  response?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  searchParameters?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  userId?: number | null;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutSearchesInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutSearchesInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutSearchesInput, {
    nullable: true,
  })
  users?: UserUpdateManyWithoutSearchesInput;
}

export { SearchUpdateInput as SearchUpdateInput };
