/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SearchService } from "../search.service";
import { SearchCreateInput } from "./SearchCreateInput";
import { Search } from "./Search";
import { SearchFindManyArgs } from "./SearchFindManyArgs";
import { SearchWhereUniqueInput } from "./SearchWhereUniqueInput";
import { SearchUpdateInput } from "./SearchUpdateInput";
import { FeedFindManyArgs } from "../../feed/base/FeedFindManyArgs";
import { Feed } from "../../feed/base/Feed";
import { FeedWhereUniqueInput } from "../../feed/base/FeedWhereUniqueInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

export class SearchControllerBase {
  constructor(protected readonly service: SearchService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Search })
  async createSearch(@common.Body() data: SearchCreateInput): Promise<Search> {
    return await this.service.createSearch({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        imageUrl: true,
        isPrivate: true,
        response: true,
        searchParameters: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        userId: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Search] })
  @ApiNestedQuery(SearchFindManyArgs)
  async searches(@common.Req() request: Request): Promise<Search[]> {
    const args = plainToClass(SearchFindManyArgs, request.query);
    return this.service.searches({
      ...args,
      select: {
        createdAt: true,
        id: true,
        imageUrl: true,
        isPrivate: true,
        response: true,
        searchParameters: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        userId: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Search })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async search(
    @common.Param() params: SearchWhereUniqueInput
  ): Promise<Search | null> {
    const result = await this.service.search({
      where: params,
      select: {
        createdAt: true,
        id: true,
        imageUrl: true,
        isPrivate: true,
        response: true,
        searchParameters: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        userId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Search })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSearch(
    @common.Param() params: SearchWhereUniqueInput,
    @common.Body() data: SearchUpdateInput
  ): Promise<Search | null> {
    try {
      return await this.service.updateSearch({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          imageUrl: true,
          isPrivate: true,
          response: true,
          searchParameters: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Search })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSearch(
    @common.Param() params: SearchWhereUniqueInput
  ): Promise<Search | null> {
    try {
      return await this.service.deleteSearch({
        where: params,
        select: {
          createdAt: true,
          id: true,
          imageUrl: true,
          isPrivate: true,
          response: true,
          searchParameters: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/feeds")
  @ApiNestedQuery(FeedFindManyArgs)
  async findFeeds(
    @common.Req() request: Request,
    @common.Param() params: SearchWhereUniqueInput
  ): Promise<Feed[]> {
    const query = plainToClass(FeedFindManyArgs, request.query);
    const results = await this.service.findFeeds(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        search: {
          select: {
            id: true,
          },
        },

        searchId: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/feeds")
  async connectFeeds(
    @common.Param() params: SearchWhereUniqueInput,
    @common.Body() body: FeedWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      feeds: {
        connect: body,
      },
    };
    await this.service.updateSearch({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/feeds")
  async updateFeeds(
    @common.Param() params: SearchWhereUniqueInput,
    @common.Body() body: FeedWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      feeds: {
        set: body,
      },
    };
    await this.service.updateSearch({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/feeds")
  async disconnectFeeds(
    @common.Param() params: SearchWhereUniqueInput,
    @common.Body() body: FeedWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      feeds: {
        disconnect: body,
      },
    };
    await this.service.updateSearch({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/users")
  @ApiNestedQuery(UserFindManyArgs)
  async findUsers(
    @common.Req() request: Request,
    @common.Param() params: SearchWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findUsers(params.id, {
      ...query,
      select: {
        accessToken: true,
        createdAt: true,
        email: true,
        firstName: true,

        friendship: {
          select: {
            id: true,
          },
        },

        fullName: true,
        id: true,
        instagramId: true,
        lastName: true,
        profilePictureUrl: true,
        refreshToken: true,
        roles: true,

        search: {
          select: {
            id: true,
          },
        },

        setting: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        username: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/users")
  async connectUsers(
    @common.Param() params: SearchWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        connect: body,
      },
    };
    await this.service.updateSearch({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/users")
  async updateUsers(
    @common.Param() params: SearchWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        set: body,
      },
    };
    await this.service.updateSearch({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/users")
  async disconnectUsers(
    @common.Param() params: SearchWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        disconnect: body,
      },
    };
    await this.service.updateSearch({
      where: params,
      data,
      select: { id: true },
    });
  }
}
