/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { FeedCreateNestedManyWithoutSearchesInput } from "./FeedCreateNestedManyWithoutSearchesInput";

import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsBoolean,
  IsInt,
  Min,
  Max,
} from "class-validator";

import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { UserCreateNestedManyWithoutSearchesInput } from "./UserCreateNestedManyWithoutSearchesInput";

@InputType()
class SearchCreateInput {
  @ApiProperty({
    required: false,
    type: () => FeedCreateNestedManyWithoutSearchesInput,
  })
  @ValidateNested()
  @Type(() => FeedCreateNestedManyWithoutSearchesInput)
  @IsOptional()
  @Field(() => FeedCreateNestedManyWithoutSearchesInput, {
    nullable: true,
  })
  feeds?: FeedCreateNestedManyWithoutSearchesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  imageUrl?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isPrivate?: boolean | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  response?: InputJsonValue;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  searchParameters?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  userId?: number | null;

  @ApiProperty({
    required: false,
    type: () => UserCreateNestedManyWithoutSearchesInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutSearchesInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutSearchesInput, {
    nullable: true,
  })
  users?: UserCreateNestedManyWithoutSearchesInput;
}

export { SearchCreateInput as SearchCreateInput };
